# Generated by Django 6.0.2 on 2026-02-28 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0002_alter_trip_driver_alter_trip_end_node_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="max_passengers",
            new_name="max_passengers_trip",
        ),
        migrations.AddField(
            model_name="trip",
            name="available_seats",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trip",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
