# Generated by Django 6.0.2 on 2026-03-02 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0003_rename_max_passengers_trip_max_passengers_trip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="departure_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When is the car leaving?"
            ),
        ),
    ]
