# Generated by Django 6.0.2 on 2026-03-03 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0004_trip_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="available_seats",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="trip",
            name="departure_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
