# Generated by Django 6.0.2 on 2026-03-03 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0005_alter_trip_available_seats_alter_trip_departure_time"),
        ("roadmap", "0002_node_adjacent_nodes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="passengers",
            field=models.ManyToManyField(
                blank=True, related_name="joined_trips", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="carpool_request",
            name="start_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passenger_trip_start",
                to="roadmap.node",
            ),
        ),
    ]
