# Generated by Django 6.0.2 on 2026-03-05 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0006_trip_passengers_alter_carpool_request_start_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpool_request",
            name="matched_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offered_trips",
                to="logic.trip",
            ),
        ),
    ]
