# Generated by Django 6.0.2 on 2026-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0007_alter_carpool_request_matched_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carpool_request",
            name="matched_trip",
        ),
        migrations.AddField(
            model_name="carpool_request",
            name="matched_trip",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="offered_trips", to="logic.trip"
            ),
        ),
    ]
