# Generated by Django 6.0.2 on 2026-03-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0008_remove_carpool_request_matched_trip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpool_request",
            name="matched_trip",
            field=models.ManyToManyField(blank=True, null=True, to="logic.trip"),
        ),
    ]
