# Generated by Django 6.0.2 on 2026-03-11 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0009_alter_carpool_request_matched_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpool_request",
            name="confirmed_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logic.trip",
            ),
        ),
        migrations.AddField(
            model_name="carpool_request",
            name="final_route",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carpool_request",
            name="matched_trip",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="offered_trips", to="logic.trip"
            ),
        ),
        migrations.AlterField(
            model_name="carpool_request",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Looking for a ride"),
                    ("Matched", "Matched with a driver"),
                    ("Completed", "Ride finished"),
                    ("Confirmed", "Ride in progress"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
