# Generated by Django 6.0.2 on 2026-03-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0010_carpool_request_confirmed_trip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpool_request",
            name="matched_trip",
            field=models.ManyToManyField(
                blank=True, related_name="offered_trips", to="logic.trip"
            ),
        ),
    ]
