# Generated by Django 6.0.2 on 2026-03-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0012_alter_carpool_request_matched_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active trip"),
                    ("Completed", "Trip finished"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
