# Generated by Django 6.0.2 on 2026-03-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0013_trip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpool_request",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Looking for a ride"),
                    ("Completed", "Ride finished"),
                    ("Confirmed", "Ride in progress"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
