# Generated by Django 6.0.2 on 2026-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0014_alter_carpool_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpool_request",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Looking for a ride"),
                    ("Confirmed", "Ride mnatched"),
                    ("In Progress", "Ride in progress"),
                    ("Completed", "Ride finished"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active trip"),
                    ("In Progress", "Trip in progress"),
                    ("Completed", "Trip finished"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
