# Generated by Django 6.0.2 on 2026-03-19 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0015_alter_carpool_request_status_alter_trip_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpool_request",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="carpool_request",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Looking for a ride"),
                    ("Confirmed", "Ride matched"),
                    ("In Progress", "Ride in progress"),
                    ("Completed", "Ride finished"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
