# Generated by Django 6.0.2 on 2026-03-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0016_alter_carpool_request_passenger_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpool_request",
            name="trip_fare",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
