# Generated by Django 6.0.2 on 2026-03-23 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0017_carpool_request_trip_fare"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpool_request",
            name="request_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
