upstream carpool_app {
    server web:8000;
}

server {
    listen 80;
    
    server_name localhost; 

    client_max_body_size 20M;

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # 5. Handle Media Files (User uploads)
    location /media/ {
        alias /app/mediafiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # 6. Pass all other requests to Django
    location / {
        proxy_pass http://carpool_app;
        
        # Standard proxy headers (helps Django know the real user IP)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;

        # Timeouts to prevent the connection from dropping during long tasks
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
    }
}