# Generated by Django 6.0.2 on 2026-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="adjacent_nodes",
            field=models.ManyToManyField(blank=True, to="roadmap.node"),
        ),
    ]
