# Generated by Django 6.0.2 on 2026-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="license_plate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_driver",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_passenger",
        ),
        migrations.AddField(
            model_name="driver",
            name="max_passengers",
            field=models.IntegerField(
                default=4, help_text="Total empty seats available for passengers"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="plate_number",
            field=models.CharField(
                default="MH 00 AA 0000", help_text="e.g., RJ 18 XY 1234", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="car_model",
            field=models.CharField(
                help_text="e.g., Maruti Suzuki Swift", max_length=100
            ),
        ),
        migrations.DeleteModel(
            name="Passenger",
        ),
    ]
