# Generated by Django 6.0.2 on 2026-02-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_driver_license_plate_remove_user_is_driver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="plate_number",
            field=models.CharField(help_text="e.g., RJ 18 XY 1234", max_length=20),
        ),
    ]
