# Generated by Django 6.0.2 on 2026-02-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_driver_plate_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="max_passengers",
            new_name="max_passengers_car",
        ),
    ]
