# Generated by Django 6.0.2 on 2026-03-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_max_passengers_driver_max_passengers_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="is_available",
        ),
    ]
