# Generated by Django 6.0.2 on 2026-03-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_driver_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="driver_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_driver",
            field=models.BooleanField(default=False),
        ),
    ]
