# Generated by Django 6.0.2 on 2026-03-19 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="Wallet.wallet",
            ),
        ),
    ]
