# Generated by Django 6.0.2 on 2026-03-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Wallet", "0002_alter_transaction_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
